### ISSUE TITLE
packageNameCompletion() does not work

### ISSUE THREAD

**Issue by hapasa** [leoafarias/pub_api_client#42]
Looking at the source, trying to find something that would just list all the available package names, I found the below function:  

/// Returns a `List<String>` of all packages listed on pub.dev
  Future<List<String>> packageNameCompletion() async

Unfortunately, that does not appear to work, but causes an unhandled exception:

Unhandled exception:
<Received error while converting exception to string>
#0      responseValidOrThrow (package:pub_api_client/src/helpers/exceptions.dart:55:7)
#1      PubClient._fetch (package:pub_api_client/src/pub_api_client_base.dart:54:5)
<asynchronous suspension>
#2      PubClient.packageNameCompletion (package:pub_api_client/src/pub_api_client_base.dart:126:18)

**Comment by hapasa** [comment]
My mistake.  The pubUrl I provided to PubClient() had a typo.
